version: 2

sources:
  - name: raw_data  # Source name
    database: stock_db  # Replace with your actual database name
    schema: raw_data  # Replace with your schema name
    tables:
      - name: incidents  # Table name
        description: "Table containing incident data with details like category, datetime, location, and resolution"
        columns:
          - name: Analysis Neighborhood
            description: "Neighborhood where the incident occurred"
          - name: Filed Online
            description: "Indicates if the report was filed online (boolean)"
          - name: Incident Category
            description: "Category of the incident"
          - name: Incident Datetime
            description: "Timestamp when the incident occurred"
          - name: Incident Day of Week
            description: "Day of the week when the incident occurred"
          - name: Incident ID
            description: "Unique identifier for the incident"
          - name: Incident Subcategory
            description: "Subcategory of the incident"
          - name: Intersection
            description: "Intersection where the incident occurred"
          - name: Latitude
            description: "Latitude coordinate of the incident"
          - name: Longitude
            description: "Longitude coordinate of the incident"
          - name: Point
            description: "Geographic point (geography type)"
          - name: Police District
            description: "Police district handling the incident"
          - name: Report Datetime
            description: "Timestamp when the report was filed"
          - name: Resolution
            description: "Resolution or outcome of the incident"


models:
  - name: moy
    description: "A model that aggregates crime incident data based on time (hour, day of week, and month)"
    columns:
      - name: month
        description: "The month of the incident (truncated from the incident datetime)"
        data_tests:
          - not_null

      - name: incident_count
        description: "The total number of crimes aggregated for the given hour, day of week, and month"
        data_tests:
          - not_null
      
      - name: covid_period
        description: "Gives information about before or after covid"
        data_tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['month', 'incident_count', 'covid_period']


  - name: dow
    description: "A model that aggregates incident counts by day of the week and categorizes them into pre-COVID and post-COVID periods"
    columns:
      - name: covid_period
        description: "Indicates whether the incident occurred in the Pre-COVID or Post-COVID period"
        data_tests:
          - not_null

      - name: incident_count
        description: "The total number of incidents grouped by day of the week and COVID period"
        data_tests:
          - not_null

  - name: geo_dis
    description: "A model that aggregates crime incident data based on the period (Pre-COVID or Post-COVID) and groups it by police district."
    columns:
      - name: police_district
        description: "The district where the incident occurred."
        data_tests:
          - not_null

      - name: covid_period
        description: "The period categorization based on Pre-COVID or Post-COVID timeframe."
        data_tests:
          - not_null
          - accepted_values:
              values: ['Pre-COVID', 'Post-COVID']

      - name: incident_count
        description: "The count of incidents in each district and period."
        data_tests:
          - not_null

  - name: hod
    description: "A model that aggregates crime incidents by hour of the day and categorizes them by COVID period (Pre-COVID or Post-COVID)."
    columns:
      - name: hour_of_day
        description: "The hour of the day (24-hour format) when the incident occurred."
        data_tests:
          - not_null
          - accepted_values:
              values: ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']

      - name: covid_period
        description: "The period categorization based on Pre-COVID or Post-COVID timeframe."
        data_tests:
          - not_null
          - accepted_values:
              values: ['Pre-COVID', 'Post-COVID']

      - name: incident_count
        description: "The count of incidents for each hour of the day and COVID period."
        data_tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['hour_of_day', 'covid_period']

  - name: inci_cat
    description: "A model that aggregates crime incidents by category and categorizes them by COVID period (Pre-COVID or Post-COVID)."
    columns:
      - name: covid_period
        description: "The period categorization based on Pre-COVID or Post-COVID timeframe."
        data_tests:
          - not_null
          - accepted_values:
              values: ['Pre-COVID', 'Post-COVID']

      - name: incident_count
        description: "The count of incidents for each category and COVID period."
        data_tests:
          - not_null
  
  - name: inci_cord
    description: "A model that aggregates crime incidents based on geographical location (latitude and longitude)."
    columns:
      - name: latitude
        description: "The latitude coordinate of the incident's location."
        data_tests:
          - not_null

      - name: longitude
        description: "The longitude coordinate of the incident's location."
        data_tests:
          - not_null

      - name: incident_count
        description: "The count of incidents for each unique geographical location."
        data_tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['latitude', 'longitude']

  - name: inci_subcat
    description: "A model that aggregates crime incidents by subcategory and categorizes them by COVID period (Pre-COVID or Post-COVID), ordered by incident count."
    columns:
      
      - name: covid_period
        description: "The period categorization based on Pre-COVID or Post-COVID timeframe."
        data_tests:
          - not_null
          - accepted_values:
              values: ['Pre-COVID', 'Post-COVID']

      - name: incident_count
        description: "The count of incidents for each subcategory and COVID period."
        data_tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['incident_subcategory', 'covid_period']
